In [1]:
import pandas as pd 
df_test = pd.read_csv('test.csv')
df_test

                      id                                       comment_text
0       00001cee341fdb12  Yo bitch Ja Rule is more succesful then you'll...
1       0000247867823ef7  == From RfC == \n\n The title is fine as it is...
2       00013b17ad220c46  " \n\n == Sources == \n\n * Zawe Ashton on Lap...
3       00017563c3f7919a  :If you have a look back at the source, the in...
4       00017695ad8997eb          I don't anonymously edit articles at all.
...                  ...                                                ...
153159  fffcd0960ee309b5  . \n i totally agree, this stuff is nothing bu...
153160  fffd7a9a6eb32c16  == Throw from out field to home plate. == \n\n...
153161  fffda9e8d6fafa9e  " \n\n == Okinotorishima categories == \n\n I ...
153162  fffe8f1340a79fc2  " \n\n == ""One of the founding nations of the...
153163  ffffce3fb183ee80  " \n :::Stop already. Your bullshit is not wel...

[153164 rows x 2 columns]

In [2]:
df_labels = pd.read_csv('test_labels.csv')
df_labels

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,-1,-1,-1,-1,-1,-1
1,0000247867823ef7,-1,-1,-1,-1,-1,-1
2,00013b17ad220c46,-1,-1,-1,-1,-1,-1
3,00017563c3f7919a,-1,-1,-1,-1,-1,-1
4,00017695ad8997eb,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...
153159,fffcd0960ee309b5,-1,-1,-1,-1,-1,-1
153160,fffd7a9a6eb32c16,-1,-1,-1,-1,-1,-1
153161,fffda9e8d6fafa9e,-1,-1,-1,-1,-1,-1
153162,fffe8f1340a79fc2,-1,-1,-1,-1,-1,-1
153163,ffffce3fb183ee80,-1,-1,-1,-1,-1,-1

In [3]:
df = pd.merge(df_test, df_labels, left_index=True, right_index=True) # merge both dataframes tgt
df = df.drop(df.columns[0], axis=1) # removing ids
df = df.drop(df.columns[1], axis=1)
df
# according to source,
# "Since the data was originally used for a Kaggle competition, 
# in the test_labels dataset there are observations with labels of value -1 indicating it was not used for scoring."

,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,Yo bitch Ja Rule is more succesful then you'll...,-1,-1,-1,-1,-1,-1
1,== From RfC == \n\n The title is fine as it is...,-1,-1,-1,-1,-1,-1
2,""" \n\n == Sources == \n\n * Zawe Ashton on Lap...",-1,-1,-1,-1,-1,-1
3,":If you have a look back at the source, the in...",-1,-1,-1,-1,-1,-1
4,I don't anonymously edit articles at all.,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...
153159,". \n i totally agree, this stuff is nothing bu...",-1,-1,-1,-1,-1,-1
153160,== Throw from out field to home plate. == \n\n...,-1,-1,-1,-1,-1,-1
153161,""" \n\n == Okinotorishima categories == \n\n I ...",-1,-1,-1,-1,-1,-1
153162,""" \n\n == """"One of the founding nations of the...",-1,-1,-1,-1,-1,-1
153163,""" \n :::Stop already. Your bullshit is not wel...",-1,-1,-1,-1,-1,-1

In [4]:
# making dataframe into appropriate format
lst = []
for i in range(len(df)):
    values = df['toxic'][i], df['severe_toxic'][i], df['obscene'][i], df['threat'][i], df['insult'][i], df['identity_hate'][i]
    lst.append(values)
    
#print(lst[:5])

dic = {0:'toxic', 1:'severe_toxic', 2:'obscene', 3:'threat', 4:'insult', 5:'identity_hate'}
result = []
for row in lst:
    temp = ""
    for i in range(len(row)):
        if row[i] == 1:
            temp += dic[i] + "|"
        elif row[i] == -1:
            temp = "-1."
        else:
            continue
        
    temp = temp[:-1]
    if temp == "":
        temp = "non_hate"
        
    result.append(temp)
    
#print(result[:5])

In [5]:
# removing "\n" from comment_text
new_text = []
for i in range(len(df)):
    new_text.append(df['comment_text'][i].replace("\n", " "))
    
df = df.drop("comment_text", axis=1)
df.insert(0, "comment_text", new_text)
    
df

,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,Yo bitch Ja Rule is more succesful then you'll...,-1,-1,-1,-1,-1,-1
1,"== From RfC == The title is fine as it is, ...",-1,-1,-1,-1,-1,-1
2,""" == Sources == * Zawe Ashton on Lapland...",-1,-1,-1,-1,-1,-1
3,":If you have a look back at the source, the in...",-1,-1,-1,-1,-1,-1
4,I don't anonymously edit articles at all.,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...
153159,". i totally agree, this stuff is nothing but...",-1,-1,-1,-1,-1,-1
153160,== Throw from out field to home plate. == D...,-1,-1,-1,-1,-1,-1
153161,""" == Okinotorishima categories == I see ...",-1,-1,-1,-1,-1,-1
153162,""" == """"One of the founding nations of the E...",-1,-1,-1,-1,-1,-1
153163,""" :::Stop already. Your bullshit is not welc...",-1,-1,-1,-1,-1,-1

In [6]:
# relabelling dataframe
#df = df.drop("label", axis=1)
df.insert(0, "label", result)
df

,label,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,-1,Yo bitch Ja Rule is more succesful then you'll...,-1,-1,-1,-1,-1,-1
1,-1,"== From RfC == The title is fine as it is, ...",-1,-1,-1,-1,-1,-1
2,-1,""" == Sources == * Zawe Ashton on Lapland...",-1,-1,-1,-1,-1,-1
3,-1,":If you have a look back at the source, the in...",-1,-1,-1,-1,-1,-1
4,-1,I don't anonymously edit articles at all.,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...
153159,-1,". i totally agree, this stuff is nothing but...",-1,-1,-1,-1,-1,-1
153160,-1,== Throw from out field to home plate. == D...,-1,-1,-1,-1,-1,-1
153161,-1,""" == Okinotorishima categories == I see ...",-1,-1,-1,-1,-1,-1
153162,-1,""" == """"One of the founding nations of the E...",-1,-1,-1,-1,-1,-1
153163,-1,""" :::Stop already. Your bullshit is not welc...",-1,-1,-1,-1,-1,-1

In [7]:
# only label and comment_text cols
df = df[["label","comment_text"]]
df

       label                                       comment_text
0         -1  Yo bitch Ja Rule is more succesful then you'll...
1         -1  == From RfC ==    The title is fine as it is, ...
2         -1  "    == Sources ==    * Zawe Ashton on Lapland...
3         -1  :If you have a look back at the source, the in...
4         -1          I don't anonymously edit articles at all.
...      ...                                                ...
153159    -1  .   i totally agree, this stuff is nothing but...
153160    -1  == Throw from out field to home plate. ==    D...
153161    -1  "    == Okinotorishima categories ==    I see ...
153162    -1  "    == ""One of the founding nations of the E...
153163    -1  "   :::Stop already. Your bullshit is not welc...

[153164 rows x 2 columns]

In [8]:
# remove rows with labels -1
df = df.drop(df[df.label == '-1'].index)
df

,label,comment_text
5,non_hate,Thank you for understanding. I think very high...
7,non_hate,:Dear god this site is horrible.
11,non_hate,"""::: Somebody will invariably try to add Relig..."
13,non_hate,""" It says it right there that it IS a type...."
14,non_hate,""" == Before adding a new product to the lis..."
...,...,...
153150,non_hate,":Jerome, I see you never got around to this…! ..."
153151,non_hate,==Lucky bastard== http://wikimediafoundation...
153154,non_hate,==shame on you all!!!== You want to speak a...
153155,toxic|obscene|insult,MEL GIBSON IS A NAZI BITCH WHO MAKES SHITTY MO...
153156,non_hate,""" == Unicorn lair discovery == Supposedl..."

In [9]:
df["label"].value_counts()

non_hate                                                  57735
toxic|obscene|insult                                       1932
toxic                                                      1710
toxic|obscene                                               854
toxic|insult                                                539
toxic|obscene|insult|identity_hate                          361
toxic|severe_toxic|obscene|insult                           176
toxic|severe_toxic|obscene|insult|identity_hate             116
toxic|insult|identity_hate                                   81
toxic|identity_hate                                          67
toxic|obscene|threat|insult                                  65
insult                                                       64
toxic|threat                                                 50
obscene                                                      49
toxic|severe_toxic|obscene                                   28
toxic|obscene|threat|insult|identity_hate                    25
toxic|severe_toxic|obscene|threat|insult                     24
toxic|obscene|identity_hate                                  20
obscene|insult                                               15
toxic|severe_toxic|obscene|threat|insult|identity_hate       14
identity_hate                                                14
toxic|threat|insult                                           9
toxic|obscene|threat                                          6
threat                                                        5
toxic|severe_toxic|threat|identity_hate                       4
toxic|severe_toxic|obscene|threat                             4
toxic|threat|identity_hate                                    4
insult|identity_hate                                          4
obscene|insult|identity_hate                                  1
toxic|severe_toxic|obscene|identity_hate                      1
threat|insult                                                 1
Name: label, dtype: int64

## Copy data to S3 Bucket

In [10]:
!pip install --upgrade  s3fs pandas  tqdm

Requirement already satisfied: s3fs in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (2023.3.0)
Requirement already satisfied: pandas in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (1.5.3)
Requirement already satisfied: tqdm in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (4.65.0)
Requirement already satisfied: aiobotocore~=2.4.2 in c:\users\guangwei\appdata\roaming\python\python39\site-packages (from s3fs) (2.4.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\guangwei\appdata\roaming\python\python39\site-packages (from s3fs) (3.8.4)
Requirement already satisfied: fsspec==2023.3.0 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from s3fs) (2023.3.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.20.3 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from pandas) (1.22.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: colorama in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from tqdm) (0.4.4)
Requirement already satisfied: wrapt>=1.10.10 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiobotocore~=2.4.2->s3fs) (1.15.0)
Requirement already satisfied: aioitertools>=0.5.1 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiobotocore~=2.4.2->s3fs) (0.11.0)
Requirement already satisfied: botocore<1.27.60,>=1.27.59 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiobotocore~=2.4.2->s3fs) (1.27.59)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\guangwei\appdata\roaming\python\python39\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.3.3)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (2.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (21.4.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (4.0.2)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (6.0.4)
Requirement already satisfied: six>=1.5 in c:\users\guangwei\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas) (1.12.0)
Requirement already satisfied: typing_extensions>=4.0 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from aioitertools>=0.5.1->aiobotocore~=2.4.2->s3fs) (4.1.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from botocore<1.27.60,>=1.27.59->aiobotocore~=2.4.2->s3fs) (1.26.10)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\guangwei\appdata\local\programs\python\python39\lib\site-packages (from botocore<1.27.60,>=1.27.59->aiobotocore~=2.4.2->s3fs) (0.10.0)
Requirement already satisfied: idna>=2.0 in c:\users\guangwei\appdata\roaming\python\python39\site-packages (from yarl<2.0,>=1.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (2.8)

In [11]:
import tqdm
import boto3
region_name='us-east-1'
import matplotlib
import os

In [ ]:
s3 = boto3.resource('s3')
s3_client = boto3.client('s3')

if (s3.Bucket(bucket_name).creation_date is None):
    #location = {'LocationConstraint': region_name}
    s3_client.create_bucket(Bucket=bucket_name)#, CreateBucketConfiguration=location)
    print ("Created bucket " + bucket_name)
else:
    print ("Bucket Exists")

In [ ]:
client = boto3.client("sts")
account_id = client.get_caller_identity()["Account"]
bucket_name = "toxic-comments" + account_id +  "-1"
print ("Bucket name used is " + bucket_name )

In [ ]:
file_name="s3://" + bucket_name + "/test_processed.csv"
print(file_name)

In [12]:
df.to_csv("test_processed.csv", header=False, index=False)

In [ ]:
# uploading to s3 bucket
s3 = boto3.client("s3")
s3.upload_file(
    Filename="test_processed.csv",
    Bucket= bucket_name,
    Key="test_processed.csv",
)

In [13]:
import json

with open('predictions.jsonl', 'r') as json_file:
    json_list = list(json_file)

data = []
for json_str in json_list:
    result = json.loads(json_str)
    data.append(result)
    
print(data[:5])

[{'File': 'test_processed.csv', 'Line': '0', 'Labels': [{'Name': 'non_hate', 'Score': 0.9998}, {'Name': 'toxic', 'Score': 0.0001}, {'Name': 'obscene', 'Score': 0.0001}]}, {'File': 'test_processed.csv', 'Line': '1', 'Labels': [{'Name': 'non_hate', 'Score': 0.8997}, {'Name': 'toxic', 'Score': 0.0841}, {'Name': 'obscene', 'Score': 0.0073}]}, {'File': 'test_processed.csv', 'Line': '2', 'Labels': [{'Name': 'non_hate', 'Score': 0.9998}, {'Name': 'toxic', 'Score': 0.0001}, {'Name': 'obscene', 'Score': 0.0001}]}, {'File': 'test_processed.csv', 'Line': '3', 'Labels': [{'Name': 'non_hate', 'Score': 0.9998}, {'Name': 'toxic', 'Score': 0.0001}, {'Name': 'obscene', 'Score': 0.0001}]}, {'File': 'test_processed.csv', 'Line': '4', 'Labels': [{'Name': 'non_hate', 'Score': 0.9998}, {'Name': 'toxic', 'Score': 0.0001}, {'Name': 'obscene', 'Score': 0.0001}]}]

In [14]:
import json

jsonString = json.dumps(data)
jsonFile = open("toxic-comments-test.json", "w")
jsonFile.write(jsonString)
jsonFile.close()